language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: test.sebastianvoss.com
  region: eu-west-1
  skip_cleanup: true
  acl: public_read
  detect_encoding: true
