language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: blog.sebastianvoss.com
  skip_cleanup: true
  detect_encoding: true
