language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: blog.sebastianvoss.com
  endpoint: blog.sebastianvoss.com.s3-website.eu-central-1.amazonaws.com
  region: Frankfurt
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  detect_encoding: true
