language: ruby
rvm:
  - 2.3.0
script: gulp
before_script:
  - npm install -g gulp
before_install:
  - npm install
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
after_success:
  _scripts/deploy
