language: node_js
node_js:
  - "5.1"
before_script:
  - npm install -g gulp
  - gem install jekyll
script: 
  - gulp jekyll
  - gulp
before_install:
  - rvm install 2.3.0
  - npm install
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
after_success:
  _scripts/deploy

