language: ruby
rvm:
  - 2.3.0
script:
  - bundle exec jekyll build
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
after_success:
  echo "Deployment to AWS S3"
  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  aws s3 cp _site s3://test.sebastianvoss.com --recursive
