#!/bin/bash

jekyll_config=$(
  case "$TRAVIS_BRANCH" in
    ("master") echo "_config.yml" ;;
    ("test")   echo "_config.yml,_config_test.yml" ;;
  esac)

if [ "$jekyll_config" == "" ]; then
  echo "Branch $TRAVIS_BRANCH is not configured in scripts/build" 
else
  jekyll build --config "$jekyll_config"
fi
