#!/bin/bash

echo "Deployment to AWS S3 (branch $TRAVIS_BRANCH)"

s3_bucket=$(
  case "$TRAVIS_BRANCH" in
    #("master") "" ;;
    ("test")   "s3://test.sebastianvoss.com" ;;
  esac)

if [[ "$s3_bucket" == "" ]]
  echo "Branch $TRAVIS_BRANCH is not configured in scripts/deploy" 
else
  aws s3 rm "$s3_bucket" --recursive
  aws s3 cp _site "$s3_bucket" --recursive
fi
