#!/bin/bash

echo "Deployment to AWS S3 (branch $TRAVIS_BRANCH)"

s3_bucket=$(
  case "$TRAVIS_BRANCH" in
    ("master") echo "" ;;
    ("test")   echo "s3://test.sebastianvoss.com" ;;
  esac)

if [ "$s3_bucket" == "" ]; then
  echo "Branch $TRAVIS_BRANCH is not configured in scripts/deploy" 
else
  find _deploy -type f -exec gzip -9 {} \; -exec mv {}.gz {} \;
  aws s3 sync _deploy "$s3_bucket" --delete --cache-control="max-age=3600" --exclude "*.css" --content-encoding "gzip"
  aws s3 sync _deploy "$s3_bucket" --delete --cache-control="max-age=604800" --include "*.css" --content-encoding "gzip"
fi
